solon:
  env: prod
  app:
    name: solonclaw
server:
  port: 12345

solonclaw:
  workspace: "./workspace"

---
solon.env.on: prod
solon:
  config:
    add: "./config.yml"

--- # 序列化
solon.serialization.json:
  dateAsFormat: 'yyyy-MM-dd HH:mm:ss' #配置日期格式（默认输出为时间戳，对 Date、LocalDateTime 有效）
  dateAsTimeZone: 'GMT+8' #配置时区
  dateAsTicks: false #将date转为毫秒数（和 dateAsFormat 二选一）
  longAsString: true #将long型转为字符串输出 （默认为false）
#  boolAsInt: false   #将bool型转为字符串输出 （默认为false）
  nullStringAsEmpty: true
  nullBoolAsFalse: false
  nullNumberAsZero: false
  nullArrayAsEmpty: true
  nullAsWriteable: true #输出所有null值
  enumAsName: true #枚举使用名字

# 日志
solon.logging.appender:
  console:
    level: INFO
    enable: true #是否启用
  file:
    name: "logs/${solon.app.name}"
    rolling: "logs/${solon.app.name}_%d{yyyy-MM-dd}_%i.log"
    level: INFO
    enable: true #是否启用
    extension: ".log"   #v2.2.18 后支持（例：.log, .log.gz, .log.zip）
    maxFileSize: "1 MB"
    maxHistory: "7" #单位：天